# Generated by Django 4.1.7 on 2023-02-18 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('bug_id', models.AutoField(default=100, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('Coding Error', 'Coding Error'), ('Design Issue', 'Design Issue'), ('Suggestion', 'Suggestion'), ('Documentation', 'Documentation'), ('Hardware', 'Hardware'), ('Query', 'Query')], max_length=20)),
                ('problem_summary', models.TextField()),
                ('problem', models.TextField()),
                ('suggested_fix', models.TextField()),
                ('reproducible', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('functional_area', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('resolution', models.CharField(max_length=100)),
                ('tested_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='release',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bug',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
        migrations.AddField(
            model_name='bugs',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs_assigned', to='bug_tracker.developer'),
        ),
        migrations.AddField(
            model_name='bugs',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_created', to='bug_tracker.author'),
        ),
        migrations.AddField(
            model_name='bugs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug_tracker.product'),
        ),
        migrations.AddField(
            model_name='bugs',
            name='report_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug_tracker.author'),
        ),
        migrations.AddField(
            model_name='bugs',
            name='resolved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug_tracker.developer'),
        ),
    ]
