# Generated by Django 4.1.7 on 2023-03-07 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0002_author_bugs_developer_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user_level', models.CharField(choices=[('Author', 'Author'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('Admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugs',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs_assigned', to='bug_tracker.employee'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_created', to='bug_tracker.employee'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='report_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to='bug_tracker.employee'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='resolved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_bugs', to='bug_tracker.employee'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
