# Generated by Django 4.0.4 on 2023-03-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0003_employee_product_date_product_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_bugs', to='bug_tracker.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
