# Generated by Django 4.0.4 on 2023-03-26 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0004_alter_bugs_resolved_by_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs_created', to='bug_tracker.employee'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_tracker.product'),
        ),
    ]
