# Generated by Django 4.0.4 on 2023-03-26 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0005_alter_bugs_created_by_alter_bugs_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='functional_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='problem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='problem_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='report_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to='bug_tracker.employee'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='report_type',
            field=models.CharField(choices=[('Coding Error', 'Coding Error'), ('Design Issue', 'Design Issue'), ('Suggestion', 'Suggestion'), ('Documentation', 'Documentation'), ('Hardware', 'Hardware'), ('Query', 'Query')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='resolution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='suggested_fix',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='tested_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
