# Generated by Django 4.0.4 on 2023-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0006_alter_bugs_comment_alter_bugs_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='bug_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
