# Generated by Django 4.0.4 on 2023-03-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0007_alter_bugs_bug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='reproducible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
