# Generated by Django 4.0.4 on 2023-03-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0008_alter_bugs_reproducible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bugs',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='bug_tracker.area'),
        ),
    ]
