# Generated by Django 4.0.4 on 2023-03-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0009_area_bugs_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='emp_id',
            new_name='area_id',
        ),
    ]
