# Generated by Django 4.0.4 on 2023-03-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0012_alter_product_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='root', max_length=100),
        ),
    ]
