# Generated by Django 4.0.4 on 2023-03-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0013_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
