# Generated by Django 4.0.4 on 2023-03-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0014_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='areas',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='release',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
